# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    photos_directory: '%kernel.project_dir%/public/'
    emailfrom: 'jpadron@gmail.com'
    urlfrom: 'http://giep-platform.pafar.com.ve/'
    urlapi: 'http://giepboffice.pafar.com.ve/public/'
    urlapilocal: 'C:/xampp/htdocs/giep/public/'
    urlapistage: 'http://bofficegiepstage.pafar.com.ve/public/'

    urlapinotification: 'http://localhost:3000/notification/all/pagined'
    urlapipaginedWithoutReading: 'http://localhost:3000/notification/all/paginedWithoutReading'
    urlapideletenotification: 'http://localhost:3000/notification/deleteNotificacion'
    urlapideleteallnotification: 'http://localhost:3000/notification/deleteAll'
    urlapinotificationpushbroadcast: 'http://localhost:3000/notification/push/broadcast'
    
services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller/'
        tags: ['controller.service_arguments']


    App\Command\GererarLogInterfase:
        arguments: ['%owncloudrouter%','%pathinterfacexecute%']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    App\Service\Helper:
        arguments:
            $manager: '@doctrine.orm.entity_manager'
            $validator: '@validator'
    
    App\Service\FileUploader:
        arguments:
            $targetDirectory: '%photos_directory%'

    App\Service\EmailFactory:
        arguments:
            $emailfrom: '%emailfrom%'

    App\Service\CodigoQR:
